spring.application.name=reviewrestaurant
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=mappings
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_reviews
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true