spring.application.name=reviewrestaurant
management.endpoints.web.exposure.include=mappings
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration